[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.7.0

[env:native]
platform = native
platform_packages = platformio/toolchain-gccmingw32
test_build_src = yes
build_flags = -std=c++11
build_src_filter = +<*> -<main.cpp>
